apiVersion: v1
kind: Secret
metadata:
  name: mysql-creds
type: Opaque
stringData:
  root: haru1004
  xtrabackup: haru1004
  monitor: monitory
  clustercheck: clustercheckpassword
  proxyadmin: admin_password
  pmmserver: admin
  operator: operatoradmin