apiVersion: v1
kind: Secret
metadata:
  name: minio-tenant-creds-secret
type: Opaque
data:
  accesskey: aGFydWJhbmQ=
  secretkey: aGFydTEwMDQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-tenant-console-secret
type: Opaque
data:
  ## Passphrase to encrypt jwt payload
  CONSOLE_PBKDF_PASSPHRASE: VmF0ZWNo
  ## Salt to encrypt jwt payload
  CONSOLE_PBKDF_SALT: VmF0ZWNo
  ## MinIO User Access Key (used for Console Login)
  CONSOLE_ACCESS_KEY: aGFydWJhbmQ=
  ## MinIO User Secret Key (used for Console Login)
  CONSOLE_SECRET_KEY: a2trazMyNDk=
---
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio-tenant
  namespace: minio-tenant
  labels:
    app: minio-tenant
  annotations:
    prometheus.io/path: /minio/v2/metrics/cluster
    prometheus.io/port: "9000"
    prometheus.io/scrpae: "true"
spec:
  requestAutoCert: false
  # certConfig:
  #   commonName: ""
  #   organizationName: []
  #   dnsNames: []
  console:
    consoleSecret:
      name: minio-tenant-console-secret
    image: minio/console:v0.7.4
    replicas: 2
  credsSecret:
    name: minio-tenant-creds-secret
  image: minio/minio:RELEASE.2021-06-07T21-40-51Z
  mountPath: /export
  pools:
  - name: pool-0
    servers: 3
    volumesPerServer: 2
    resources:
      requests:
        memory: 2Gi
        cpu: 500m
      limits:
        memory: 6Gi
        cpu: 2
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      metadata: 
        name: minio-volume-claim
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 30Gi
        storageClassName: openebs-hostpath
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: DoesNotExist
            weight: 1  
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: v1.min.io/tenant
              operator: In
              values:
              - minio-tenant
            - key: v1.min.io/pool
              operator: In
              values:
                - pool-0
          topologyKey: kubernetes.io/hostname
  serviceMetadata:
    minioServiceLabels:
      label: minio-svc
    minioServiceAnnotations:
      v2.min.io: minio-svc
    consoleServiceLabels:
      label: console-svc
    consoleServiceAnnotations:
      v2.min.io: console-svc

