apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 7.13.2
  count: 1
  elasticsearchRef:
    name: elasticsearch-cluster
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  podTemplate:
    metadata:
      labels:
        app: elasticsearch
        
    spec:
      automountServiceAccountToken: true
      containers:
          - name: kibana
            env:
              - name: NODE_OPTIONS
                value: "--max-old-space-size=2048"
            resources:
              requests:
                memory: 1Gi
                cpu: 250m
              limits:
                memory: 2Gi
                cpu: 250m
